module.exports = {
  ON_SET_VEHICLES: 'ON_SET_VEHICLES',
  ON_ADD_VEHICLE: 'ON_ADD_VEHICLE',
  ON_SEARCH_ERROR: 'ON_SEARCH_ERROR',
  ON_RESET_STORE: 'ON_RESET_STORE',
  ON_SET_INFORME_DATA: 'ON_SET_INFORME_DATA',
};
